// <auto-generated />
using System;
using ImdbApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220715210916_AddDefaultDataInDatabase")]
    partial class AddDefaultDataInDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImdbApi.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a10e1c6-1290-468e-94e6-d2b1c4df2e3b"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5586),
                            Description = "Movie 1 Descriptions",
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44871444-adca-4cc6-bbd5-872af479ced8"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5595),
                            Description = "Movie 1 Descriptions",
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("38cd7009-0ce1-45d6-9738-f59b8dbd89e0"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5597),
                            Description = "Movie 2 Descriptions",
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 8.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("5e0cd383-3720-4590-9d2a-ac9af625c622"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5599),
                            Description = "Movie 3 Descriptions",
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 7.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e4542652-2191-40e9-86c1-77258b932e22"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5607),
                            Description = "Movie 4 Descriptions",
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 10.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4aaed804-1768-4ac3-8bf5-cd323fa7617a"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5609),
                            Description = "Movie 5 Descriptions",
                            Name = "Movie 5",
                            ReleaseDate = "2019",
                            Score = 6.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("617ac8bb-baf9-4315-9084-2e2a4b6b3a5e"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5611),
                            Description = "Movie 6 Descriptions",
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 4.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("8040b6f5-2f3f-4e4c-af9b-4cbeff886b3f"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5613),
                            Description = "Movie 6 Descriptions",
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("664c3a1a-8fc6-4aa7-a571-692bb4b106db"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 9, 16, 602, DateTimeKind.Local).AddTicks(5614),
                            Description = "Movie 6 Descriptions",
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
