// <auto-generated />
using System;
using ImdbApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220715211624_AddLikeColumnDataInDatabase")]
    partial class AddLikeColumnDataInDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImdbApi.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71e5f31f-a11f-4b6b-b903-5adc6cdcddaf"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6583),
                            Description = "Movie 1 Descriptions",
                            Like = 3,
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("b317fe62-db4c-41a3-8f03-26c59163d0e1"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6595),
                            Description = "Movie 1 Descriptions",
                            Like = 15,
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("d2daff69-9403-42d6-b9f8-ffc8944ddd8f"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6597),
                            Description = "Movie 2 Descriptions",
                            Like = 20,
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 8.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("67611fc5-a2e5-4612-84c8-c485d6e247c8"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6598),
                            Description = "Movie 3 Descriptions",
                            Like = 30,
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 7.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("184ce48a-2e09-42c6-b1f1-8e3dd1d07a31"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6600),
                            Description = "Movie 4 Descriptions",
                            Like = 40,
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 10.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("ccb360e8-d5f1-4334-ba89-e652dab2634e"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6602),
                            Description = "Movie 5 Descriptions",
                            Like = 60,
                            Name = "Movie 5",
                            ReleaseDate = "2019",
                            Score = 6.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("d806e889-0039-40b6-88ac-fe80e65de3dd"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6603),
                            Description = "Movie 6 Descriptions",
                            Like = 150,
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 4.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("841b8d7d-738e-4781-9b9e-23496774941d"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6605),
                            Description = "Movie 6 Descriptions",
                            Like = 160,
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a8446b8b-e9c2-4b65-b284-6b5b870c5e95"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 16, 24, 270, DateTimeKind.Local).AddTicks(6609),
                            Description = "Movie 6 Descriptions",
                            Like = 100,
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
