// <auto-generated />
using System;
using ImdbApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220715211313_AddLikeColumnInMovieTable")]
    partial class AddLikeColumnInMovieTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImdbApi.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ce1f813-63d9-4840-8735-3c49f4aa145a"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(769),
                            Description = "Movie 1 Descriptions",
                            Like = 0,
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("59887d97-299f-40d4-a65e-5f8efc24b99f"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(780),
                            Description = "Movie 1 Descriptions",
                            Like = 0,
                            Name = "Movie 1",
                            ReleaseDate = "2019",
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("13866839-4f8a-490d-a0c8-c90e385daeb2"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(782),
                            Description = "Movie 2 Descriptions",
                            Like = 0,
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 8.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("b8d51c79-c92f-423d-9ccc-49983aed9a5f"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(784),
                            Description = "Movie 3 Descriptions",
                            Like = 0,
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 7.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4af5c42c-6e52-40f5-aac9-d4c0f1d01416"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(786),
                            Description = "Movie 4 Descriptions",
                            Like = 0,
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 10.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("dfb017f8-4e68-4e52-be28-10e2561773a2"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(787),
                            Description = "Movie 5 Descriptions",
                            Like = 0,
                            Name = "Movie 5",
                            ReleaseDate = "2019",
                            Score = 6.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("59065058-8b51-4d11-a4bc-b048dab87d8f"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(789),
                            Description = "Movie 6 Descriptions",
                            Like = 0,
                            Name = "Movie 4",
                            ReleaseDate = "2019",
                            Score = 4.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("7edf8900-8be3-44b2-b73a-69bdb64f6778"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(791),
                            Description = "Movie 6 Descriptions",
                            Like = 0,
                            Name = "Movie 3",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("f74d4114-99d4-42d5-bc13-1a9f0cf344a2"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 13, 13, 623, DateTimeKind.Local).AddTicks(795),
                            Description = "Movie 6 Descriptions",
                            Like = 0,
                            Name = "Movie 2",
                            ReleaseDate = "2019",
                            Score = 3.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
