// <auto-generated />
using System;
using ImdbApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220715212335_AddReleaseColumnDataInDatabase")]
    partial class AddReleaseColumnDataInDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImdbApi.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c7fbf6b-d609-48f7-9fc4-9a0b6d16264a"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4020),
                            Description = "Movie 1 Descriptions",
                            Like = 3,
                            Name = "Movie 1",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("40d945d8-fe91-4d34-afe6-54310a9955e7"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4034),
                            Description = "Movie 1 Descriptions",
                            Like = 15,
                            Name = "Movie 1",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("3158b220-40fc-4a88-8218-a081e06101b4"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4037),
                            Description = "Movie 2 Descriptions",
                            Like = 20,
                            Name = "Movie 2",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("1f19365b-0ff9-4c73-9c4e-0b9d5db6a8b3"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4040),
                            Description = "Movie 3 Descriptions",
                            Like = 30,
                            Name = "Movie 3",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 7.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("bac65cb8-5dae-4a80-b421-3796698b36f7"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4043),
                            Description = "Movie 4 Descriptions",
                            Like = 40,
                            Name = "Movie 4",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 10.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("54e6d1b5-6d14-4aa1-817e-9a6e9b3fdc77"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4053),
                            Description = "Movie 5 Descriptions",
                            Like = 60,
                            Name = "Movie 5",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 6.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("45fa30c5-1df4-4755-9e17-b622c1bb5aea"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4056),
                            Description = "Movie 6 Descriptions",
                            Like = 150,
                            Name = "Movie 4",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 4.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4dc4ba44-715b-4e37-ad33-2ddfbd314891"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4059),
                            Description = "Movie 6 Descriptions",
                            Like = 160,
                            Name = "Movie 3",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 3.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("0ad87b1d-6ec2-4848-b33d-ac95e014695c"),
                            CreatedDate = new DateTime(2022, 7, 16, 0, 23, 35, 320, DateTimeKind.Local).AddTicks(4061),
                            Description = "Movie 6 Descriptions",
                            Like = 100,
                            Name = "Movie 2",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 3.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
