// <auto-generated />
using System;
using ImdbApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ImdbApi.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8607203-6b8f-4ff5-b94c-7d4dba390c40"),
                            Certificate = "13+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6657),
                            Description = "Movie 1 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 3,
                            Name = "Movie 1",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a737ccf6-860f-4981-91e0-8e93e9d8af17"),
                            Certificate = "12+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6671),
                            Description = "Movie 1 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 15,
                            Name = "Movie 1",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("81d3a760-38de-46f5-aa55-5d2b829e86e2"),
                            Certificate = "13+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6674),
                            Description = "Movie 2 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 20,
                            Name = "Movie 2",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("848d967a-3c9e-45af-a7ad-8cefc2ee6d82"),
                            Certificate = "13+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6676),
                            Description = "Movie 3 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 30,
                            Name = "Movie 3",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 7.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("85bc62a5-2346-4722-9f31-6c17e0f962a8"),
                            Certificate = "18+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6678),
                            Description = "Movie 4 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 40,
                            Name = "Movie 4",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 10.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("50e53d1a-a136-4722-970b-0ff13f764605"),
                            Certificate = "7+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6680),
                            Description = "Movie 5 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 60,
                            Name = "Movie 5",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 6.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("5abb4135-9fd3-4d73-9ca3-0dc5911ca299"),
                            Certificate = "7+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6682),
                            Description = "Movie 6 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 150,
                            Name = "Movie 4",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 4.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e9d4e692-7555-4ef6-bed7-b81174c40a0b"),
                            Certificate = "18+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6697),
                            Description = "Movie 6 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 160,
                            Name = "Movie 3",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 3.0,
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("f5902d5e-0840-4db8-bf70-aa617532e774"),
                            Certificate = "13+",
                            CreatedDate = new DateTime(2022, 7, 18, 12, 59, 43, 32, DateTimeKind.Local).AddTicks(6699),
                            Description = "Movie 6 Descriptions",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg",
                            Like = 100,
                            Name = "Movie 2",
                            ReleaseDate = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 3.0,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
